// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeopleManagement.Infrastructure.Persistence;

#nullable disable

namespace PeopleManagement.Infrastructure.Migrations
{
    [DbContext(typeof(PeopleManagementDbContext))]
    [Migration("20260322000000_AddPropriedadesHistoricas")]
    partial class AddPropriedadesHistoricas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("PeopleManagement.Infrastructure.Persistence.Entities.ClassificacaoPerfilEntity", b =>
                {
                    b.Property<Guid>("LideradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAtualizacaoUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NineBox")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LideradoId");

                    b.ToTable("ClassificacoesPerfil", (string)null);
                });

            modelBuilder.Entity("PeopleManagement.Infrastructure.Persistence.Entities.CulturaAvaliacaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AprenderEMelhorarSempre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtitudeDeDono")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuscarMelhoresResultadosParaClientes")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("EspiritoDeEquipe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Excelencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FazerAcontecer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InovarParaInspirar")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LideradoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LideradoId", "Data")
                        .IsUnique();

                    b.ToTable("CulturaAvaliacoes", (string)null);
                });

            modelBuilder.Entity("PeopleManagement.Infrastructure.Persistence.Entities.DiscEntity", b =>
                {
                    b.Property<string>("IdLiderado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdLiderado", "Data");

                    b.ToTable("Disc", (string)null);
                });

            modelBuilder.Entity("PeopleManagement.Infrastructure.Persistence.Entities.FeedbackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LideradoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Polaridade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Receptividade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LideradoId", "Data");

                    b.ToTable("Feedbacks", (string)null);
                });

            modelBuilder.Entity("PeopleManagement.Infrastructure.Persistence.Entities.InformacoesPessoaisEntity", b =>
                {
                    b.Property<Guid>("LideradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AspiracaoCarreira")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataContratacao")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataInicioCargo")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GostosPessoais")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("QuantidadeFilhos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RedFlags")
                        .HasColumnType("TEXT");

                    b.HasKey("LideradoId");

                    b.ToTable("InformacoesPessoais", (string)null);
                });

            modelBuilder.Entity("PeopleManagement.Infrastructure.Persistence.Entities.LideradoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Liderados", (string)null);
                });

            modelBuilder.Entity("PeopleManagement.Infrastructure.Persistence.Entities.OneOnOneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LideradoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProximosAssuntos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TarefasAcordadas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LideradoId", "Data");

                    b.ToTable("OneOnOnes", (string)null);
                });

            modelBuilder.Entity("PeopleManagement.Infrastructure.Persistence.Entities.TooltipEntity", b =>
                {
                    b.Property<string>("ChaveCampo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChaveCampo");

                    b.ToTable("Tooltips", (string)null);
                });

            modelBuilder.Entity("PeopleManagement.Infrastructure.Persistence.Entities.PropriedadeHistoricaEntity", b =>
                {
                    b.Property<string>("IdLiderado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdLiderado", "Tipo", "Data");

                    b.HasIndex("IdLiderado", "Tipo");

                    b.ToTable("PropriedadesHistoricas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}

